### ISSUE TITLE
Is there an easy way to grab the data from all waves, as opposed to just the latest?

### ISSUE THREAD

**Issue by davidkane9** [TheUpshot/2018-live-poll-results#1]
The data directory only keeps the most recent polling wave. For example, the data/ directory currently shows:

elections-poll-az06-3.csv

But not the two previous polls for this district. (I believe the -3 means that this is the 3rd Upshot/Siena poll for Arizona 6th,

**Comment by m1arc00** [comment]
The 3 mostly describes when we polled a district. We're visiting some districts (including Arizona 6) for the first time in our third wave. For districts we poll more than once, both csvs will be in the directory (For example: elections-poll-il12-1.csv and elections-poll-il12-3.csv)
